### ISSUE TITLE
ENOENT when running notes new "sample string"

### ISSUE THREAD

**Issue by Peter-AMD** [Hendrixer/intro-node-v3#1]
I forked the repo, as you can see here in the image, I tried running the new note command but it fails because it can't find the file.
![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/6dd2e42e-3e2c-4263-8cd4-c8bfd5883d1a)

I was able to fix it though by removing the "pathname" at DB_PATH inside the db.js file
![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/6a82a8cd-1a1f-48c0-aae2-76e408c944e8)

**Comment by Peter-AMD** [comment]
Hi @dtauer thank you for responding.
The issue still persist even with "db.json", the only fix for it is to remove the ".pathname" under "db.js"

![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/dfbb3902-d686-4fcf-89cd-7deac532a1cc)

**Comment by dtauer** [comment]
@Peter-AMD Did you include the default notes object in the db.json?
```json
{
   "notes": []
}
```

**Comment by Peter-AMD** [comment]
![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/ce5e4b80-a8c5-41af-9337-141cd02964d8)
Yes @dtauer

**Comment by Peter-AMD** [comment]
Maybe the node version?
I'm using 18.7
![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/1c2395f7-7ca9-46c3-b39a-71abd55f1843)

**Comment by Peter-AMD** [comment]
![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/9ff6c805-5b36-4c76-bf25-1a6fc38092a3)
If I remove the "pathname" it works just fine.

**Comment by dtauer** [comment]
Just tested a clean fork with both Node `18.17.1` and `18.9.0` and didn't get the ENOENT error. After forking the repo into my own account, here's what I did:

```bash
git clone https://github.com/dtauer/intro-node-v3.git
cd intro-node-v3
npm i
npm link
note new "New Note Title"
```

No ENOENT error. In general, the code in the repo is the final version so users should be starting from scratch.

**Comment by Peter-AMD** [comment]
I checked the node documentation for readFile earlier today, @dtauer , that's how I manage to fix the issue.
Might be weird issue, not sure why is it like this. I'm on Windows 10, but thank you for responding..
https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fspromisesreadfilepath-options

![image](https://github.com/Hendrixer/intro-node-v3/assets/28400709/a1f48695-03aa-4f35-8fd8-5076a88cbe04)
